/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_ASW_DI 0x00u        /*!<@brief Analog switch is open (disabled) */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_FUNC6 0x06u         /*!<@brief Selects pin function 6 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_13_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_14_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_15_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_15_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO0_16_FUNC_ALT2 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_17_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_11_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_11_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_20_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO1_20_FUNC_ALT5 0x05u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_21_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO1_21_FUNC_ALT5 0x05u

/*! @name PIO0_13 (number 71), VS
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_CAMERA_VS_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_CAMERA_VS_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */
#define PINSFUNC_CAMERA_VS_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_CAMERA_VS_PIN 13U                   /*!<@brief PORT pin number */
#define PINSFUNC_CAMERA_VS_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_14 (number 72), HS
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_CAMERA_HS_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_CAMERA_HS_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */
#define PINSFUNC_CAMERA_HS_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_CAMERA_HS_PIN 14U                   /*!<@brief PORT pin number */
#define PINSFUNC_CAMERA_HS_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_15 (number 22), PCLK
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_CAMERA_PCLK_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_CAMERA_PCLK_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */
#define PINSFUNC_CAMERA_PCLK_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_CAMERA_PCLK_PIN 15U                   /*!<@brief PORT pin number */
#define PINSFUNC_CAMERA_PCLK_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO0_17 (number 8), PDWN
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_CAMERA_PDWN_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_CAMERA_PDWN_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */
#define PINSFUNC_CAMERA_PDWN_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_CAMERA_PDWN_PIN 17U                   /*!<@brief PORT pin number */
#define PINSFUNC_CAMERA_PDWN_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO1_11 (number 93), DEBUG
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_CAMERA_DEBUG_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_CAMERA_DEBUG_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */
#define PINSFUNC_CAMERA_DEBUG_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_CAMERA_DEBUG_PIN 11U                   /*!<@brief PORT pin number */
#define PINSFUNC_CAMERA_DEBUG_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_16 (number 14), XCLK
  @{ */
#define PINSFUNC_CAMERA_XCLK_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_CAMERA_XCLK_PIN 16U                   /*!<@brief PORT pin number */
#define PINSFUNC_CAMERA_XCLK_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO1_20 (number 4), SCL
  @{ */
#define PINSFUNC_CAMERA_SCL_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_CAMERA_SCL_PIN 20U                   /*!<@brief PORT pin number */
#define PINSFUNC_CAMERA_SCL_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO1_21 (number 30), SDA
  @{ */
#define PINSFUNC_CAMERA_SDA_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_CAMERA_SDA_PIN 21U                   /*!<@brief PORT pin number */
#define PINSFUNC_CAMERA_SDA_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PinsFunc_camera(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO1_1_FUNC_ALT5 0x05u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_2_FUNC_ALT6 0x06u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_3_FUNC_ALT6 0x06u

/*! @name PIO1_2 (number 61), SCK
  @{ */
#define PINSFUNC_LCD_SPI_SCK_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_LCD_SPI_SCK_PIN 2U                   /*!<@brief PORT pin number */
#define PINSFUNC_LCD_SPI_SCK_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO0_26 (number 60), MOSI
  @{ */
#define PINSFUNC_LCD_SPI_MOSI_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_LCD_SPI_MOSI_PIN 26U                   /*!<@brief PORT pin number */
#define PINSFUNC_LCD_SPI_MOSI_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO1_3 (number 62), MISO
  @{ */
#define PINSFUNC_LCD_SPI_MISO_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_LCD_SPI_MISO_PIN 3U                   /*!<@brief PORT pin number */
#define PINSFUNC_LCD_SPI_MISO_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO1_1 (number 59), SSEL
  @{ */
#define PINSFUNC_LCD_SPI_SSEL_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_LCD_SPI_SSEL_PIN 1U                   /*!<@brief PORT pin number */
#define PINSFUNC_LCD_SPI_SSEL_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PinsFunc_LCD_SPI(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
